# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-04 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table=None,
        ),
    ]
